[package]
name = "sol_chess"
version = "0.1.1"
edition = "2021"

[dependencies]
argh = "0.1.13"
indicatif = "0.17.9"
rand = "0.8.5"

[profile.release]
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
